# Generated by Django 3.2.4 on 2021-10-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_password', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_description', models.TextField(max_length=500)),
                ('company_photo', models.FileField(upload_to='company_photo/')),
                ('company_number', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_email', models.EmailField(max_length=254, unique=True)),
                ('coordinator_password', models.CharField(max_length=32)),
                ('coordinator_name', models.CharField(max_length=200)),
                ('coordinator_photo', models.FileField(upload_to='company_photo/')),
                ('coordinator_number', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_id', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('student_cpr', models.CharField(max_length=9, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('student_gpa', models.FloatField(default=3.0)),
                ('student_college', models.CharField(max_length=50)),
                ('student_department', models.CharField(max_length=50)),
                ('student_course', models.CharField(max_length=7)),
                ('student_number', models.CharField(max_length=8, unique=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_nationality', models.CharField(max_length=32)),
                ('student_photo', models.FileField(upload_to='student_photo/')),
                ('student_resume', models.FileField(upload_to='student_photo/')),
                ('student_transcript', models.FileField(upload_to='student_photo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_doctor', models.CharField(max_length=50)),
                ('recommendation_pdf', models.FileField(upload_to='student_photo/')),
                ('recommendation_upload_date', models.DateTimeField(verbose_name='Date Uploaded')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppotunity_title', models.CharField(max_length=50)),
                ('oppotunity_description', models.TextField(max_length=500)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_report_pdf', models.FileField(upload_to='student_photo/')),
                ('final_report_submission_date', models.DateTimeField(verbose_name='date submitted')),
                ('final_report_question_01', models.CharField(max_length=32)),
                ('final_report_question_02', models.CharField(max_length=32)),
                ('final_report_question_03', models.CharField(max_length=32)),
                ('final_report_question_04', models.CharField(max_length=32)),
                ('final_report_question_05', models.CharField(max_length=32)),
                ('final_report_question_06', models.CharField(max_length=32)),
                ('final_report_question_07', models.CharField(max_length=32)),
                ('final_report_question_08', models.CharField(max_length=32)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_evaluation_pdf', models.FileField(upload_to='student_photo/')),
                ('coordinator_evaluation_submission_date', models.DateTimeField(verbose_name='date submitted')),
                ('coordinator_evaluation_question_01', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_02', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_03', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_04', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_05', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_06', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_07', models.CharField(max_length=32)),
                ('coordinator_evaluation_question_08', models.CharField(max_length=32)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.coordinator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_evaluation_pdf', models.FileField(upload_to='student_photo/')),
                ('company_evaluation_submission_date', models.DateTimeField(verbose_name='date submitted')),
                ('company_evaluation_question_01', models.CharField(max_length=32)),
                ('company_evaluation_question_02', models.CharField(max_length=32)),
                ('company_evaluation_question_03', models.CharField(max_length=32)),
                ('company_evaluation_question_04', models.CharField(max_length=32)),
                ('company_evaluation_question_05', models.CharField(max_length=32)),
                ('company_evaluation_question_06', models.CharField(max_length=32)),
                ('company_evaluation_question_07', models.CharField(max_length=32)),
                ('company_evaluation_question_08', models.CharField(max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='Date Applied')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_pdf', models.FileField(upload_to='student_photo/')),
                ('acceptance_upload_date', models.DateTimeField(verbose_name='date uploaded')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorapp.student')),
            ],
        ),
    ]
