# Generated by Django 3.2.4 on 2021-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='academic_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_college',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_cpr',
            new_name='cpr',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_gpa',
            new_name='gpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_nationality',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_resume',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_transcript',
            new_name='transcript',
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(default='student', editable=False, max_length=7),
        ),
    ]
